### ISSUE TITLE
Ansible Role to install Sentry based on docker-compose.yml file

### ISSUE THREAD

**Issue by harobed** [Its-Alex/sentry-docker-example#4]
Hi,

I have created a Ansible Role to install Sentry based on docker-compose.yml file, like in your project.

- [ansible-role-sentry](https://github.com/harobed/ansible-role-sentry)
- and [Ansible Role Sentry usage demonstration](https://github.com/harobed/ansible-role-sentry-example) repository

I suggest to add this references in your README 😉

Best regards,
Stéphane

**Comment by Its-Alex** [comment]
Done in #5
